//Create order
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

//My orders
export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

//My order details
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

//Fetch orders by admin
export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAIL = "ADMIN_ORDERS_FAIL";

//Update Product by admin
export const ADMIN_UPDATE_ORDER_REQUEST = "ADMIN_UPDATE_ORDER_REQUEST";
export const ADMIN_UPDATE_ORDER_SUCCESS = "ADMIN_UPDATE_ORDER_SUCCESS";
export const ADMIN_UPDATE_ORDER_RESET = "ADMIN_UPDATE_ORDER_RESET";
export const ADMIN_UPDATE_ORDER_FAIL = "ADMIN_UPDATE_ORDER_FAIL";

//Delete Product by admin
export const ADMIN_DELETE_ORDER_REQUEST = "ADMIN_DELETE_ORDER_REQUEST";
export const ADMIN_DELETE_ORDER_SUCCESS = "ADMIN_DELETE_ORDER_SUCCESS";
export const ADMIN_DELETE_ORDER_RESET = "ADMIN_DELETE_ORDER_RESET";
export const ADMIN_DELETE_ORDER_FAIL = "ADMIN_DELETE_ORDER_FAIL";

//Clear error
export const CLEAR_ERRORS = "CLEAR_ERRORS";