//Fetch Products
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

//Fetch Products by admin
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

//Create Product by admin
export const ADMIN_CREATE_PRODUCT_REQUEST = "ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS = "ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_RESET = "ADMIN_CREATE_PRODUCT_RESET";
export const ADMIN_CREATE_PRODUCT_FAIL = "ADMIN_CREATE_PRODUCT_FAIL";

//Update Product by admin
export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";

//Delete Product by admin
export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_RESET = "ADMIN_DELETE_PRODUCT_RESET";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";

//Fetch details of the product
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

//Add review of the product
export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_RESET = "ADD_REVIEW_RESET";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";

//Reviews of the product by admin
export const ADMIN_REVIEWS_REQUEST = "ADMIN_REVIEWS_REQUEST";
export const ADMIN_REVIEWS_SUCCESS = "ADMIN_REVIEWS_SUCCESS";
export const ADMIN_REVIEWS_FAIL = "ADMIN_REVIEWS_FAIL";

//Delete review of the product by admin
export const ADMIN_DELETE_REVIEW_REQUEST = "ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS = "ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_RESET = "ADMIN_DELETE_REVIEW_RESET";
export const ADMIN_DELETE_REVIEW_FAIL = "ADMIN_DELETE_REVIEW_FAIL";

//Clear error
export const CLEAR_ERRORS = "CLEAR_ERRORS";